qc_dump: Handle non-writable /tmp
Seems like there's cases where /tmp is not writable - oh my...

Signed-off-by: Stefan Raspl <raspl@linux.ibm.com>

diff --git a/qc_dump b/qc_dump
--- a/qc_dump
+++ b/qc_dump
@@ -32,7 +32,11 @@ fi
 
 echo "Adding further content...";
 cd /tmp
-dump="`ls -rtd qclib-??????.dump-1 | tail -1`";
+dump="`ls -rtd qclib-??????.dump-1 2>/dev/null | tail -1`";
+if [ "$dump" == "" ]; then
+	echo "Error: No dump data found, sorry";
+	exit 3;
+fi
 mv ref_result.txt $dump;
 lscpu -e			> $dump/lscpu.output;
 hostname			> $dump/hostname.output;
